---
server:           domaincontroller1.yourdomain.lan	#FQDN of the Domain Controller you want to Authenticate with for administration
port:             389					#LDAP port that should be used -- default 389
base:             DC=yourdomain,DC=lan			#LDAP search base -- DC=yourdomain,DC=lan will search the entire LDAP structure
domain:           yourdomain.lan			#Your AD domain -- example yourdomain.lan or yourdomain.com
admin_group:      Domain Admins				#Name of the LDAP Group that the user must be a member of to log into the interface and administer it
